# Generated by Django 3.1.2 on 2022-10-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BPago',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField()),
                ('monto_pago', models.IntegerField()),
                ('tipo_pago', models.IntegerField()),
                ('nombre_conservador', models.IntegerField()),
            ],
            options={
                'db_table': 'B_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarCompra',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CAR_COMPRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cbr',
            fields=[
                ('id_cbr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cbr', models.CharField(max_length=100)),
                ('correo_cbr', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'CBR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClasProp',
            fields=[
                ('id_clas', models.AutoField(primary_key=True, serialize=False)),
                ('foja', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('anno', models.DateTimeField()),
                ('razon_social', models.CharField(blank=True, max_length=45, null=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'CLAS_PROP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'COMUNA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calle', models.CharField(max_length=45)),
                ('numero_casa', models.IntegerField()),
            ],
            options={
                'db_table': 'DIRECCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_doc', models.CharField(max_length=45)),
                ('doc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DuennoProp',
            fields=[
                ('id_duenno', models.AutoField(primary_key=True, serialize=False)),
                ('rut_duenno', models.CharField(max_length=15)),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(max_length=45)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(max_length=45)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'DUENNO_PROP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_error', models.CharField(max_length=45)),
                ('mensaje_error', models.CharField(max_length=100)),
                ('fecha_error', models.DateTimeField()),
            ],
            options={
                'db_table': 'ERROR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'ESTADO_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_form', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo_form', models.CharField(max_length=45)),
                ('asunto_form', models.CharField(max_length=45)),
                ('detalle_form', models.CharField(max_length=500)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'FORMULARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorAtencion',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dias_atencion', models.CharField(max_length=45)),
                ('horario_apertura', models.CharField(max_length=10)),
                ('horario_cierre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'HOR_ATENCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PROPIEDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'PROVINCIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'REGION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_soli', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('estado', models.CharField(max_length=45)),
                ('numero_seguimiento', models.CharField(max_length=45)),
                ('comentario', models.CharField(blank=True, db_column='Comentario', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SOLICITUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipodoc', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipop', models.IntegerField(db_column='id_tipoP', primary_key=True, serialize=False)),
                ('nombre_tipop', models.CharField(db_column='nombre_tipoP', max_length=45)),
            ],
            options={
                'db_table': 'TIPO_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id_tipop', models.IntegerField(db_column='id_tipoP', primary_key=True, serialize=False)),
                ('nombre_tipop', models.CharField(db_column='nombre_tipoP', max_length=45)),
            ],
            options={
                'db_table': 'TIPO_PROPIEDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPago',
            fields=[
                ('id_tipop', models.IntegerField(db_column='id_tipoP', primary_key=True, serialize=False)),
                ('nombre_tipop', models.CharField(db_column='nombre_tipoP', max_length=45)),
            ],
            options={
                'db_table': 'T_PAGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id_tramite', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tramite', models.CharField(max_length=100)),
                ('valor_tramite', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TRAMITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTramite',
            fields=[
                ('id_tipot', models.AutoField(db_column='id_tipoT', primary_key=True, serialize=False)),
                ('nombre_tipot', models.CharField(db_column='nombre_tipoT', max_length=45)),
            ],
            options={
                'db_table': 'T_TRAMITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUsuario',
            fields=[
                ('id_tipou', models.IntegerField(db_column='id_tipoU', primary_key=True, serialize=False)),
                ('nombre_tipou', models.CharField(db_column='nombre_tipoU', max_length=45)),
            ],
            options={
                'db_table': 'T_USUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=15)),
                ('contrasenna', models.CharField(max_length=100)),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('primer_apellido', models.CharField(max_length=45)),
                ('segundo_apellido', models.CharField(max_length=45)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
    ]
