# Generated by Django 3.1.2 on 2022-11-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controlador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFormulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_form', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('correo_form', models.CharField(max_length=45)),
                ('asunto_form', models.CharField(max_length=45)),
                ('detalle_form', models.CharField(max_length=500)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'FORMULARIO',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
